# Generated by Django 5.2.11 on 2026-02-10 13:52

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='セミナー名')),
                ('description', models.TextField(verbose_name='詳細')),
            ],
            options={
                'verbose_name': 'セミナー',
                'verbose_name_plural': '「セミナー」 一覧',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='レクチャー名')),
                ('content', markdownx.models.MarkdownxField(verbose_name='コンテンツ')),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar_base2.seminar', verbose_name='セミナー')),
            ],
            options={
                'verbose_name': 'レクチャー',
                'verbose_name_plural': '「レクチャー」 一覧',
            },
        ),
    ]
