# Generated by Django 5.2.11 on 2026-02-11 10:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_base2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['id'], 'verbose_name': 'レクチャー', 'verbose_name_plural': '「レクチャー」 一覧'},
        ),
        migrations.AlterModelOptions(
            name='seminar',
            options={'ordering': ['id'], 'verbose_name': 'セミナー', 'verbose_name_plural': '「セミナー」 一覧'},
        ),
        migrations.AddField(
            model_name='lecture',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
