# Generated by Django 5.2.11 on 2026-02-12 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_base2', '0002_alter_lecture_options_alter_seminar_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar_base2.seminar', verbose_name='セミナー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '参加者',
                'verbose_name_plural': '「参加者」 一覧',
                'ordering': ['user__username'],
                'constraints': [models.UniqueConstraint(fields=('user', 'seminar'), name='unique_member_per_seminar')],
            },
        ),
    ]
