# Generated by Django 5.2.11 on 2026-04-29 07:47

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_base2', '0003_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='コンテンツ'),
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
    ]
