# Generated by Django 5.2.11 on 2026-04-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_base2', '0004_seminar_content_delete_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='content',
            field=models.TextField(blank=True, verbose_name='コンテンツ'),
        ),
    ]
