# Generated by Django 5.2.11 on 2026-04-30 01:57

import django.db.models.deletion
import seminar_base2.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_base2', '0005_alter_seminar_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('file', models.FileField(upload_to=seminar_base2.models.get_seminar_file_path, verbose_name='ファイル')),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar_base2.seminar', verbose_name='セミナー')),
            ],
            options={
                'verbose_name': 'ファイル',
                'verbose_name_plural': '「ファイル」 一覧',
                'ordering': ['id'],
            },
        ),
    ]
