# Generated by Django 5.2.11 on 2026-05-01 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_base2', '0006_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminar',
            options={'ordering': ['-id'], 'verbose_name': 'セミナー', 'verbose_name_plural': '「セミナー」 一覧'},
        ),
        migrations.AddField(
            model_name='members',
            name='last_access',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='最終アクセス日時'),
        ),
        migrations.AddField(
            model_name='members',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='進捗'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='manage',
            field=models.BooleanField(default=False, verbose_name='管理モード'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar_base2.seminar', verbose_name='セミナー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'マネージャー',
                'verbose_name_plural': '「マネージャー」 一覧',
                'ordering': ['user__username'],
                'constraints': [models.UniqueConstraint(fields=('user', 'seminar'), name='unique_manager_per_seminar')],
            },
        ),
    ]
