# Generated by Django 5.2.11 on 2026-05-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_base2', '0007_alter_seminar_options_members_last_access_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['name'], 'verbose_name': 'ファイル', 'verbose_name_plural': '「ファイル」 一覧'},
        ),
        migrations.AddField(
            model_name='seminar',
            name='public',
            field=models.BooleanField(default=False, verbose_name='公開'),
        ),
    ]
