# Generated by Django 5.2.11 on 2026-05-15 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_base2', '0008_alter_file_options_seminar_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='seminar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='seminar_base2.seminar', verbose_name='セミナー'),
        ),
        migrations.AlterField(
            model_name='members',
            name='seminar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='seminar_base2.seminar', verbose_name='セミナー'),
        ),
    ]
