# Generated by Django 5.2.11 on 2026-06-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_base2', '0010_resetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='last_request',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='最終リクエスト日時'),
        ),
        migrations.AddField(
            model_name='members',
            name='request',
            field=models.BooleanField(default=False, verbose_name='リクエスト'),
        ),
    ]
