# Generated by Django 5.2.11 on 2026-06-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_base2', '0011_members_last_request_members_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ファイル名'),
        ),
    ]
