# Generated by Django 5.2.11 on 2026-09-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_base2', '0012_alter_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='join',
            field=models.BooleanField(default=False, verbose_name='参加受付状態'),
        ),
        migrations.AddField(
            model_name='members',
            name='join_issued_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='参加受付発行日時'),
        ),
        migrations.AddField(
            model_name='members',
            name='join_uuid',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True, verbose_name='参加受付UUID'),
        ),
        migrations.AddField(
            model_name='members',
            name='last_join',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='参加受付日時'),
        ),
    ]
