# Generated by Django 5.2.11 on 2026-09-29 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_base2', '0013_members_join_members_join_issued_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='join_issued_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='参加受付コード発行日時'),
        ),
        migrations.AlterField(
            model_name='members',
            name='join_uuid',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True, verbose_name='参加受付コード'),
        ),
        migrations.CreateModel(
            name='NoSettingPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '設定権限なし',
                'verbose_name_plural': '「設定権限なし」 一覧',
            },
        ),
    ]
