# Generated by Django 5.2.11 on 2026-09-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_base2', '0014_alter_members_join_issued_at_alter_members_join_uuid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'ordering': ['user__username'], 'verbose_name': '受講者', 'verbose_name_plural': '「受講者」 一覧'},
        ),
        migrations.AlterModelOptions(
            name='nosettingpermission',
            options={'verbose_name': '設定機能制限', 'verbose_name_plural': '「設定機能制限」 一覧'},
        ),
        migrations.AddField(
            model_name='seminar',
            name='join_flag',
            field=models.BooleanField(default=False, verbose_name='参加受付状況'),
        ),
        migrations.AlterField(
            model_name='members',
            name='join',
            field=models.BooleanField(default=False, verbose_name='参加受付'),
        ),
    ]
