name: Python test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: app
        run: pip install -r requirements.txt

      - name: Run check
        working-directory: app
        run: python3 manage.py check

      - name: Run test
        working-directory: app
        run: python3 manage.py test